### ISSUE TITLE
Unable to install custom schema

### ISSUE THREAD

**Issue by LeshaKaras-lang** [primer-io/primer-sdk-ios#435]
Hi 🙂, i have some problem with SDK (pod 'PrimerSDK', '= 2.3.0')
Unable to set custom schema, because schema is injected into dependency container in PrimerSettings, but gets according to the protocol PrimerThemeProtocol. As a result, it always initializes an empty schema and adds dependencies to the package.

I have some fix for this bug

    `public func configure(settings: PrimerSettings? = nil, delegate: PrimerDelegate? = nil) {
        DependencyContainer.register((settings ?? PrimerSettings()) as PrimerSettingsProtocol)
        DependencyContainer.register((settings ?? PrimerSettings()).uiOptions.theme as PrimerThemeProtocol)
        self.delegate = delegate
    }`

**Comment by d4r1091** [comment]
Thanks for the proposed change @LeshaKaras-lang. I believe we also have a PR open, addressing the same issue.
We are in the process of releasing a planned update of our SDK.
We will evaluate and include a fix for this issue in the next release plan.
