### ISSUE TITLE
Paypal vaulting not working

### ISSUE THREAD

**Issue by Josefnm** [primer-io/primer-sdk-ios#519]
sdk version: 2.11.1
xcode: 13.2.1
device: simulator, iphone 12, ios 15.2
react native sdk: 2.11.0
react native version: 0.66.4

I'm posting it here since the error seems to be in the ios code. It works fine on android.

I am trying to vault paypal payment method (create billing agrement) using either showPaymentMethod or showVaultManager. The flow seemingly works fine until it reaches the end, where nothing happens once I am returned to the app from the paypal page.

I poked around a bit in your code and it looks like PayPalService is instantly deinitialized, which means that paypalTokenId is nil.

![image](https://user-images.githubusercontent.com/5729730/194022898-d051e5ad-7fae-4146-b0bc-326b384ab3a1.png)

Logged what's happening
// showPaymentMethod:
🧨 start startBillingAgreementSession
🧨 deinit
🧨 success startBillingAgreementSession
🧨 config.tokenId: BA-4S778055VB884092R
🧨 self?.paypalTokenId: nil
// after paypal flow finished:
🧨 start confirmBillingAgreement
// nothing seems to happen here with the error for missing value paypalTokenId. No error is logged or event received by my error handler.
🧨 deinit

**Comment by xevious78** [comment]
Thanks for raising an issue @Josefnm. The team will soon look into it 👌 I will keep you updated!

**Comment by d4r1091** [comment]
This as been fixed @Josefnm in the latest `2.14.1` version.
Closing
