### ISSUE TITLE
Error uploading to appstore

### ISSUE THREAD

**Issue by Josefnm** [primer-io/primer-sdk-ios#555]
primer sdk: 2.15.0
 xcode: 13.2.1 (upgrading to 14 isn't viable right now)
 
 [Transporter Error Output]: ERROR ITMS-90535: Unexpected CFBundleExecutable Key. The bundle at 'Payload/BRICK.app/PrimerResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

**Comment by Josefnm** [comment]
Noticed this is fixed in 2.15.1

**Comment by xevious78** [comment]
Thanks for confirming @Josefnm!
