### ISSUE TITLE
Failed to import Primer3DS on Release mode

### ISSUE THREAD

**Issue by robert-go** [primer-io/primer-sdk-ios#565]
![Screenshot 2023-01-16 at 15 47 25](https://user-images.githubusercontent.com/64536259/212635647-fec5582d-030b-48b3-9d35-d582be7b6c9a.png)

# Steps to reproduce
1. Clone this repo, master branch
2. Go to `Example` folders, `pod install`
3. Change build configuration to Release
![Screenshot 2023-01-16 at 15 48 54](https://user-images.githubusercontent.com/64536259/212635928-61523c52-7ad9-43de-80fd-2538cc9702f4.png)

# Environment
- OS: macOS 13.1
- Xcode: 14.2
- KlarnaMobileSDK (2.2.2)
- Primer3DS (1.0.3)
- PrimerKlarnaSDK (1.0.4)
- PrimerSDK (2.16.1)
- Device: Simulator

**Comment by jnewc** [comment]
Unable to recreate this and user account is inactive, so let's close for now.
