### ISSUE TITLE
Xcode15 compilation fail due to lack of UIKit import in Mock3DSService:

### ISSUE THREAD

**Issue by katleta3000** [primer-io/primer-sdk-ios#695]
There is an actual problem with building PrimerSDK 2.17.5 installed via SPM using Xcode 15 (15A240d)
Mock3DSService fails to compile due to a lack of import of the UIKit framework.
Adding `import UIKit` to line #9 in `Mock3DSService.swift` fixes the issue.
Please add this fix to the next build

<img width="413" alt="Mock3DSService_1" src="https://github.com/primer-io/primer-sdk-ios/assets/1257625/de84e84a-c383-456e-8a0d-dca2e36b0419">

<img width="961" alt="Mock3DSService_2" src="https://github.com/primer-io/primer-sdk-ios/assets/1257625/e3dd7203-7bbc-4358-828a-926c9c3a591f">

**Comment by katleta3000** [comment]
@NQuinn27 Hi, thank you for your quick noticing and fixing
When do you plan to make a new public version?

**Comment by NQuinn27** [comment]
Hi @katleta3000, thanks for bringing this to our attention.
We plan to release this fix asap. I will update this issue when the new version is released.

**Comment by NQuinn27** [comment]
2.17.6 has been released which resolves this issue
