### ISSUE TITLE
Migrate from PKPaymentAuthorizationViewController to PKPaymentAuthorizationController 

### ISSUE THREAD

**Issue by katleta3000** [primer-io/primer-sdk-ios#710]
Hi guys,

Recently, I've spent lots of time debugging `PrimerSDK` due to a mysterious case when the native `PKPaymentAuthorizationViewController` was not shown on the device. The problem was caused by the wrong `merchantIdentifier` (not the same as in the certificate). But the problem is not apparent, and you have to spend time to detect that the error is inside  `PKPaymentAuthorizationViewController` from `PassKit.framework`

The investigating process highlighted that you use `PKPaymentAuthorizationViewController` in `ApplePayTokenizationViewModel.swift`, but starting iOS10 (as I see from the `Package.swift`, it's your min deployment target) there is a new recommended way from Apple to use [`PKPaymentAuthorizationController`](https://developer.apple.com/documentation/passkit/pkpaymentauthorizationcontroller)

**Why to use?**

1. Simplify this tricky code of showing the Apple Pay screen

`PrimerUIManager.primerRootViewController?.present(paymentVC, animated: true, completion: {`
  `DispatchQueue.main.async {`
    `PrimerDelegateProxy.primerHeadlessUniversalCheckoutUIDidShowPaymentMethod(for: self.config.type)`
    `self.didPresentPaymentMethodUI?()`
    `seal.fulfill()`
  `}`
`})`

2. Potentially, you may remove the logic of creating a custom `UIWindowScene` in `static func prepareRootViewController()` (`PrimerUIManager.swift`) because the `PKPaymentAuthorizationController` is shown by Apple's framework inner logic. And it's guaranteed to be at the top of the hierarchy

`let paymentVC = PKPaymentAuthorizationController(paymentRequest: request)`
`paymentVC.present { success in`
`if success {`
`print("Presented payment controller")` 
`} else {`
`print("Failed to present payment controller")`
`}`
`}}`

4. Due to the code above, you would be able to return some error saying that the problem is in `PassKit.framework` but not your own.
5. This migration will lead you to a `UKit` independent future (for example, for MacOS or WatchOS or just SwiftUI usage)

**Comment by NQuinn27** [comment]
Hi @katleta3000,

Thanks for reaching out, and for the detailed summary. This looks like a positive change, we will take this into consideration in our backlog.
